//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangeSystemConfugration
    {
        public int ID { get; set; }
        public string SupportEmail { get; set; }
        public byte[] otherEmail { get; set; }
        public string SupportPhoneNo { get; set; }
        public string FaceBookURL { get; set; }
        public string TwitterURL { get; set; }
        public string LinkedinURL { get; set; }
        public string DefaultBookImage { get; set; }
        public string DefaultUserImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
