//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Profile
    {
        public int ID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }

        
        public Nullable<int> Gender { get; set; }
        public string SecondaryEmailAddress { get; set; }
        public string PhoneNumberCountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ProfilePic { get; set; }

     //   [Required(ErrorMessage ="Enter the addres")]
        public string AddressLine1 { get; set; }

    //    [Required(ErrorMessage = "Enter the addres")]
        public string AddressLine2 { get; set; }

    //    [Required(ErrorMessage = "Enter the addres")]
        public string City { get; set; }

        [Required(ErrorMessage = "Enter the addres")]
        public string State { get; set; }

        [Required(ErrorMessage = "Enter the addres")]
        public string ZipCode { get; set; }

        [Required(ErrorMessage = "Enter the addres")]
        public string Country { get; set; }
        public string University { get; set; }
        public string College { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ReferenceData ReferenceData { get; set; }
        public virtual User User { get; set; }

       
        public HttpPostedFileBase UserProfilePic { get; set; }
    }
}
